name    'jaydub-resource_factory'
version '1.0.0'
author 'John Morton'
license 'Apache License, Version 2.0'
summary 'A means to create and configure resources from Hiera'
description 'resource_factory is a wrapper around create_resources that allows you to specify a hiera key to configure arbitrary resources from. Use the defined type to create factories for each of your resources, and the class to bootstrap the factories via hiera's node classifier and class property look up.'
project_page 'https://github.com/jaydub/resource_factory'
